from typing import Optional, List
from services.config_service import ConfigService

class WebSpriteConfig:
    def __init__(self, moniker, log_service):
        ### Some what important to set these to your needs ###
        # Content
        self.welcome_message: str = '"ima tell you about the {}."'
        self.short_message: str = '"<@{}>, brevity is the soul of wit, but not of good queries. Please provide more details in your request."'
        self.message_start: str = '"Running request... relax, chill, and vibe a minute."'
        self.message_end: str = '"Generated by: gpt-4. Memory not enabled. Has no knowledge of past or current queries. For code see https://github.com/ShelbyJenkins/shelby-as-a-service."'
        ### Don't touch anything below here ###
        self.moniker: str = moniker
        self.platform: str = 'web'
        # Populates variables from .env or from container env
        ConfigService(self, log_service)
        # Destructuring strings
        # "" are required for formating in github actions workflow, but they need to be removed for use by discord sprite
        self.welcome_message: str = self.welcome_message.strip('"')
        self.short_message: str = self.short_message.strip('"')
        self.message_start: str = self.message_start.strip('"')
        self.message_end: str = self.message_end.strip('"')